version: '3'

services:
  back:
    build: ./
    container_name: back-container
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_CONNECTION_STRING: mongodb://localhost:27017/learnwords
   

  
 