version: '3'

services:
  back:
    build: ./
    container_name: back-container
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/learnwords
    networks:
      name: rslang_be
      external: true
